-- MySQL Script generated by MySQL Workbench
-- Mon 05 Jun 2017 07:45:48 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rpgBot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rpgBot` ;

-- -----------------------------------------------------
-- Schema rpgBot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rpgBot` DEFAULT CHARACTER SET utf8 ;
USE `rpgBot` ;

-- -----------------------------------------------------
-- Table `rpgBot`.`guild`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rpgBot`.`guild` ;

CREATE TABLE IF NOT EXISTS `rpgBot`.`guild` (
  `id` CHAR(18) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpgBot`.`weapon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rpgBot`.`weapon` ;

CREATE TABLE IF NOT EXISTS `rpgBot`.`weapon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lvl` INT NOT NULL DEFAULT 0,
  `attackPower` INT NOT NULL DEFAULT 0,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpgBot`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rpgBot`.`user` ;

CREATE TABLE IF NOT EXISTS `rpgBot`.`user` (
  `id` CHAR(18) NOT NULL,
  `weapon_id` INT NULL,
  `name` VARCHAR(200) NOT NULL,
  `lvl` INT NULL DEFAULT 0,
  `xp` INT NULL DEFAULT 0,
  `hp` INT NULL DEFAULT 50,
  `maxHp` INT NULL DEFAULT 50,
  `maxItems` INT NULL DEFAULT 50,
  `attackPower` INT NULL DEFAULT 5,
  `defense` INT NULL DEFAULT 5,
  PRIMARY KEY (`id`),
  INDEX `fk_user_weapon1_idx` (`weapon_id` ASC),
  CONSTRAINT `fk_user_weapon1`
    FOREIGN KEY (`weapon_id`)
    REFERENCES `rpgBot`.`weapon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpgBot`.`guild_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rpgBot`.`guild_has_user` ;

CREATE TABLE IF NOT EXISTS `rpgBot`.`guild_has_user` (
  `guild_id` CHAR(18) NOT NULL,
  `user_id` CHAR(18) NOT NULL,
  PRIMARY KEY (`guild_id`, `user_id`),
  INDEX `fk_guild_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_guild_has_user_guild_idx` (`guild_id` ASC),
  CONSTRAINT `fk_guild_has_user_guild`
    FOREIGN KEY (`guild_id`)
    REFERENCES `rpgBot`.`guild` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guild_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rpgBot`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpgBot`.`armor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rpgBot`.`armor` ;

CREATE TABLE IF NOT EXISTS `rpgBot`.`armor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lvl` INT NOT NULL DEFAULT 0,
  `defense` INT NOT NULL DEFAULT 0,
  `name` VARCHAR(45) NOT NULL,
  `armorType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpgBot`.`user_has_armor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rpgBot`.`user_has_armor` ;

CREATE TABLE IF NOT EXISTS `rpgBot`.`user_has_armor` (
  `user_id` CHAR(18) NOT NULL,
  `armor_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `armor_id`),
  INDEX `fk_user_has_armor_armor1_idx` (`armor_id` ASC),
  INDEX `fk_user_has_armor_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_armor_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rpgBot`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_armor_armor1`
    FOREIGN KEY (`armor_id`)
    REFERENCES `rpgBot`.`armor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpgBot`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rpgBot`.`item` ;

CREATE TABLE IF NOT EXISTS `rpgBot`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `lvl` INT NOT NULL DEFAULT 0,
  `hp` INT NULL,
  `defense` INT NULL,
  `attackPower` INT NULL,
  `armorType` VARCHAR(45) NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpgBot`.`user_has_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rpgBot`.`user_has_item` ;

CREATE TABLE IF NOT EXISTS `rpgBot`.`user_has_item` (
  `user_id` CHAR(18) NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `item_id`),
  INDEX `fk_user_has_item_item1_idx` (`item_id` ASC),
  INDEX `fk_user_has_item_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_item_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rpgBot`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_item_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `rpgBot`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
